[env:esp32dev]
platform  = espressif32@3.5.0
board     = esp32dev
framework = arduino

monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=0
    -DESP32

lib_deps =
    https://github.com/eloquentarduino/EloquentTinyML.git

upload_speed = 921600